version: '3'
services:
  app:
    image:  34.229.202.159/financeapp/app-finace
    ports:
     - "8090:8080"
    links:
     - db
    networks:
     - connector

  db:
    image:  34.229.202.159/financeapp/mysql-finance
    ports:
     - "3306:3306"
    container_name: mysqldb
    environment:
       MYSQL_ROOT_PASSWORD: admin
    volumes:
     - database:/var/lib/mysql
    networks:
     - connector
networks:
  connector: {}

volumes:
  database: {}

