version: '3'
services:
  app:
    build: .
    ports:
     - "8080:8080"
    links:
     - db
    networks:
     - connector

  db:
    image:  priyarani94/mysql-v
    ports:
     - "3306:3306"
    container_name: mysqldb
    environment:
       MYSQL_ROOT_PASSWORD: admin
    volumes:
     - database:/var/lib/mysql
    networks:
     - connector
networks:
  connector: {}

volumes:
  database: {}

